### ISSUE TITLE
SGDBoop Not Applying Icons

### ISSUE THREAD

**Issue by murdocksblock** [SteamGridDB/SGDBoop#92]
This didn't used to happen, but now when attempting to apply game icons (.ico) with SGDBoop, nothing happens. Restarting Steam etc. doesn't help.

**Comment by maaya1989** [comment]
same here nothing's working for the moment.

**Comment by doZennn** [comment]
Fixed in [1.3.x](https://github.com/SteamGridDB/SGDBoop/releases/tag/v1.3.1)

**Comment by TomSalvador90** [comment]
Using latest version and having the same problem.

**Comment by HYhkLOsa** [comment]
yeah it still doesn't work for me either

**Comment by ameliarat** [comment]
Double confirming. Bug is ocurring on latest version on the AUR

**Comment by rmia46** [comment]
On Fedora 43, Installed version 1.3.1.  The problem still persists.

**Comment by isorropisths** [comment]
Is this issue back? I can't apply Icons, the rest are fine.

**Comment by mpaterakis** [comment]
ICO files are not supported by the Steam Client. We'll have to send PNGs instead for those.

**Comment by isorropisths** [comment]
I was referring to steamgriddb not applying the icons any more using SGDBoop

**Comment by mpaterakis** [comment]
Those icons are .ico files, and boop downloads them and places them in the correct path, but the Steam Client is unable to load them, because it's essentially just a chromium browser. The site's API needs to be updated so it sends a supported file format like PNG/WEBP, so that the Steam Client can render them.

**Comment by isorropisths** [comment]
I can see in Steam/userdata/<id>/config/grid that the icons of the specific games are indeed .png files, but still not applying in Steam. This only started happening the last few days.

**Comment by mpaterakis** [comment]
I didn't mean their filenames, I meant their content. They are renamed to what Steam Client expects, but they are still ico files.

Anyway, this is something that needs to be fixed on the site's end, will keep this issue open until then.

**Comment by krug91** [comment]
Still not working.

**Comment by fxzzi** [comment]
This broke for me recently too, haven't been able to set icons on any games. Rest of the items work fine though

**Comment by CYCLOP5** [comment]
As @mpaterakis mentioned:

> I didn't mean their filenames, I meant their content. They are renamed to what Steam Client expects, but they are still ico files.
> Anyway, this is something that needs to be fixed on the site's end, will keep this issue open until then.

Steam requires true PNG header data, but SGDBoop currently renames downloaded assets without re-encoding the underlying container.

For anyone hitting this on Windows, here is a PS workaround using ImageMagick (`winget install ImageMagick.ImageMagick`). It's an inplace replacer:
Just change the 1st line accordingly:
```powershell
$grid = "C:\Program Files (x86)\Steam\userdata\YOUR_STEAM_ID_HERE\config\grid"
if (-not (Test-Path $grid)) {
    Write-Host "check ure dir: $grid"
    return
}
$files = @(Get-ChildItem -Path $grid -Filter "*_icon.*" -File)
foreach ($file in $files) {
    Write-Host "in progress $($file.Name)..."
    $temp = Join-Path $env:TEMP "$([guid]::NewGuid()).png"

    & magick "$($file.FullName)[0]" -background none -alpha on "$temp" 2>$null

    if ($LASTEXITCODE -eq 0 -and (Test-Path $temp) -and (Get-Item $temp).Length -gt 0) {
        Move-Item $temp "$($file.FullName)" -Force
        Write-Host "lgtm: $($file.Name)"
    }
    else {
        Remove-Item $temp -Force -ErrorAction SilentlyContinue
        Write-Host "issue: $($file.Name)"
    }
}
```
might have to restart steam idk.

The [0] flag flattens animated WebPs/GIFs into static PNG icons. If you want to keep icons animated, swap line
```powershell
& magick "$($file.FullName)[0]" -background none -alpha on "$temp" 2>$null
```
to: 
```powershell
& magick "$($file.FullName)" -coalesce "apng:$temp" 2>$null
```
Though I haven't tested this since I don't have any animated icons so uh good luck. (in theory it should work but theory only takes you so far)

**Comment by GerasSB** [comment]
> As [@mpaterakis](https://github.com/mpaterakis) mentioned:
> 
> > I didn't mean their filenames, I meant their content. They are renamed to what Steam Client expects, but they are still ico files.
> > Anyway, this is something that needs to be fixed on the site's end, will keep this issue open until then.
> 
> Steam requires true PNG header data, but SGDBoop currently renames downloaded assets without re-encoding the underlying container.
> 
> For anyone hitting this on Windows, here is a PS workaround using ImageMagick (`winget install ImageMagick.ImageMagick`). It's an inplace replacer: Just change the 1st line accordingly:
> 
> $grid = "C:\Program Files (x86)\Steam\userdata\YOUR_STEAM_ID_HERE\config\grid"
> if (-not (Test-Path $grid)) {
>     Write-Host "check ure dir: $grid"
>     return
> }
> $files = @(Get-ChildItem -Path $grid -Filter "*_icon.*" -File)
> foreach ($file in $files) {
>     Write-Host "in progress $($file.Name)..."
>     $temp = Join-Path $env:TEMP "$([guid]::NewGuid()).png"
> 
>     & magick "$($file.FullName)[0]" -background none -alpha on "$temp" 2>$null
> 
>     if ($LASTEXITCODE -eq 0 -and (Test-Path $temp) -and (Get-Item $temp).Length -gt 0) {
>         Move-Item $temp "$($file.FullName)" -Force
>         Write-Host "lgtm: $($file.Name)"
>     }
>     else {
>         Remove-Item $temp -Force -ErrorAction SilentlyContinue
>         Write-Host "issue: $($file.Name)"
>     }
> }
> might have to restart steam idk.
> 
> The [0] flag flattens animated WebPs/GIFs into static PNG icons. If you want to keep icons animated, swap line
> 
> & magick "$($file.FullName)[0]" -background none -alpha on "$temp" 2>$null
> to:
> 
> & magick "$($file.FullName)" -coalesce "apng:$temp" 2>$null
> Though I haven't tested this since I don't have any animated icons so uh good luck. (in theory it should work but theory only takes you so far)

This worked perfectly for me thank you! Pretty funny coincidence that I ran into this solution right as it was posted lol

The strange thing is (prior to this fix) SGDBoop's icons sometimes work and they randomly break. Sometimes it happens after adding other games' icons, sometimes it happens suddenly. It's quite strange, we'll see if this solution doesn't run into the same issue.

**Comment by lonykaras4-dev** [comment]
Same here

**Comment by lonykaras4-dev** [comment]
Found a fix: renaming icons from JPG to PNG and manually picking them.

**Comment by Arcitec** [comment]
@doZennn It's still bugged unfortunately. People's diagnosis saying that the icon needs to be a .png (real PNG) seems correct. So SGDBoop needs to do a format conversion.

Edit: Actually not...

```bash
$ cd ~/.local/share/Steam/userdata/*/config/grid

$ ls -l
-rw-r--r--. 1 johnny johnny 6399574 Sep 10 19:25 2423109739_hero.png
-rw-r--r--. 1 johnny johnny   66459 Sep 10 19:26 2423109739_icon.png
-rw-r--r--. 1 johnny johnny 2507792 Sep 10 19:26 2423109739_logo.png
-rw-r--r--. 1 johnny johnny  163763 Sep 10 19:25 2423109739p.jpg
-rw-r--r--. 1 johnny johnny  926147 Sep 13 05:10 3105373198_hero.jpg
-rw-r--r--. 1 johnny johnny 1535253 Sep 13 05:11 3105373198_icon.png
-rw-r--r--. 1 johnny johnny  131852 Sep 13 05:11 3105373198_logo.png
-rw-r--r--. 1 johnny johnny 1146582 Sep 13 05:10 3105373198p.png

$ for f in *.png; do file $f; done
2423109739_hero.png: PNG image data, 3840 x 1240, 8-bit/color RGB, non-interlaced
2423109739_icon.png: PNG image data, 256 x 256, 8-bit/color RGBA, non-interlaced
2423109739_logo.png: PNG image data, 3363 x 556, 8-bit/color RGBA, non-interlaced
3105373198_icon.png: PNG image data, 1024 x 1024, 8-bit/color RGBA, non-interlaced
3105373198_logo.png: PNG image data, 8565 x 849, 8-bit colormap, non-interlaced
3105373198p.png: PNG image data, 600 x 900, 8-bit/color RGB, non-interlaced

$ for f in *.jpg; do file $f; done
2423109739p.jpg: JPEG image data, JFIF standard 1.01, resolution (DPCM), density 28x28, segment length 16, baseline, precision 8, 600x900, components 3
3105373198_hero.jpg: JPEG image data, JFIF standard 1.01, resolution (DPI), density 72x72, segment length 16, baseline, precision 8, 1920x620, components 3

$ for f in *.png; do ffprobe $f 2>&1 | grep Stream; done
  Stream #0:0: Video: png, rgb24(pc, gbr/unknown/unknown), 3840x1240, 25 fps, 25 tbr, 25 tbn
  Stream #0:0: Video: png, rgba(pc, gbr/unknown/unknown), 256x256, 25 fps, 25 tbr, 25 tbn
  Stream #0:0: Video: png, rgba(pc, gbr/unknown/unknown), 3363x556, 25 fps, 25 tbr, 25 tbn
  Stream #0:0: Video: png, rgba(pc, gbr/unknown/unknown), 1024x1024, 25 fps, 25 tbr, 25 tbn
  Stream #0:0: Video: png, pal8(pc, gbr/unknown/unknown), 8565x849, 25 fps, 25 tbr, 25 tbn
  Stream #0:0: Video: png, rgb24(pc, gbr/bt709/iec61966-2-1), 600x900 [SAR 3779:3779 DAR 2:3], 25 fps, 25 tbr, 25 tbn

$ for f in *.jpg; do ffprobe $f 2>&1 | grep Stream; done
  Stream #0:0: Video: mjpeg (Baseline), yuvj444p(pc, bt470bg/unknown/unknown), 600x900 [SAR 28:28 DAR 2:3], 25 fps, 25 tbr, 25 tbn
  Stream #0:0: Video: mjpeg (Baseline), yuvj420p(pc, bt470bg/unknown/unknown), 1920x620 [SAR 72:72 DAR 96:31], 25 fps, 25 tbr, 25 tbn
```

Actually, it's thoroughly verified that the newest SGDBoop saves PNG files as `.png` and JPG files as `.jpg`. And the numbers correspond to the "compatdata" internal ID assigned to each non-steam game. So I have no idea why Steam isn't detecting these icons.
